local module = {
	["Tips"] = {
		"Rada: długie przebywanie w ośrodku osłabia siły witalne, staraj sie ograniczać czas jaki tam spedzasz.",
		"Rada: unikanie konfrontacji czesto gwarantuje mniejsze konsekwencje i szybszy powrót do domu."
	},	
	["Funfacts"] = {
		",,A kto powiedział że życie jest sprawiedliwe?''<br />- kapral Beton",
		",,Chodźmy się zabawić!''<br />-Haramb"
	},
	["LoadingScreenImages"] = {
		["Placeholder"] = "rbxassetid://87051128328075",
		["RealImages"] = {
			"rbxassetid://82083620185353"
		}
	},
}

return module